language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 0.10

before_script:
  - npm install -g grunt-cli

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
notifications:
  irc: "irc.freenode.org#phony"